#!/bin/sh

FQDN=`hostname -f`
DEBRELEASE=`lsb_release -cs`

echo ********************** >> /var/log/apt-security-updates
date +%Y-%m-%d-UTC-%H:%M:%S >> /var/log/apt-security-updates
echo ********************** >> /var/log/apt-security-updates

aptitude update >> /var/log/apt-security-updates

aptitude safe-upgrade -o Aptitude::Delete-Unused=true --assume-yes --target-release $DEBRELEASE-security >> /var/log/apt-security-updates

echo "[OK] Debian $DEBRELEASE security updates (if any) installed on $FQDN."
